services:
  personal-assistant-mcp-client:
    build: .
    volumes:
      - ./:/app
    env_file:
      - ./.env
    develop:
      watch:
        - path: ./modules/
          action: rebuild
        - path: ./main.py
          action: rebuild
        - path: ./docker-compose.yml
          action: rebuild
        - path: ./docker-compose.dev.yml
          action: rebuild
        - path: ./Dockerfile
          action: rebuild